"""update chat message and chat session

Revision ID: 2377040f4f25
Revises: 9abeaf034ab5
Create Date: 2026-05-28 22:41:50.122740

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2377040f4f25"
down_revision: Union[str, Sequence[str], None] = "9abeaf034ab5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_messages", sa.Column("session_id", sa.Uuid(), nullable=False))
    op.alter_column(
        "chat_messages",
        "tool_calls",
        existing_type=sa.VARCHAR(),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "chat_messages", "tool_call_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "chat_messages",
        "tokens_used",
        existing_type=sa.VARCHAR(),
        type_=sa.INTEGER(),
        nullable=True,
        postgresql_using="tokens_used::integer",
    )
    op.drop_constraint(
        op.f("chat_messages_project_id_fkey"), "chat_messages", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("chat_messages_user_id_fkey"), "chat_messages", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "chat_messages", "chat_sessions", ["session_id"], ["id"]
    )
    op.drop_column("chat_messages", "user_id")
    op.drop_column("chat_messages", "project_id")
    op.drop_column("chat_sessions", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_sessions",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "chat_messages",
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "chat_messages",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "chat_messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("chat_messages_user_id_fkey"),
        "chat_messages",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("chat_messages_project_id_fkey"),
        "chat_messages",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.alter_column(
        "chat_messages",
        "tokens_used",
        existing_type=sa.INTEGER(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "chat_messages", "tool_call_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "chat_messages",
        "tool_calls",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("chat_messages", "session_id")
    # ### end Alembic commands ###
