"""Initial upgrade

Revision ID: 908c3f253ae3
Revises: 
Create Date: 2026-05-23 20:43:48.468866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908c3f253ae3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('stripe_product_id', sa.String(), nullable=False))
    op.alter_column('plans', 'max_projects',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'max_tokens_per_day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plans', 'max_previews',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'plans', ['stripe_price_id'])
    op.create_unique_constraint(None, 'plans', ['stripe_product_id'])
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_unique_constraint(None, 'subscriptions', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_constraint(None, 'plans', type_='unique')
    op.drop_constraint(None, 'plans', type_='unique')
    op.alter_column('plans', 'max_previews',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plans', 'max_tokens_per_day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plans', 'max_projects',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plans', 'stripe_product_id')
    # ### end Alembic commands ###
