"""add stripe_customer_id to users

Revision ID: 9abeaf034ab5
Revises: 908c3f253ae3
Create Date: 2026-05-26 20:38:39.338339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abeaf034ab5'
down_revision: Union[str, Sequence[str], None] = '908c3f253ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
